version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - app-network
      
  # Configuración de php-fpm
  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: prueba
      MARIADB_USER: 1-17-0170
      MARIADB_PASSWORD: 1-17-0170
      MARIADB_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  #Docker Networks
  networks:
    app-network:
      driver: bridge